version: '3'
services:

  web:
    build: .
    volumes:
      - .:/practice-test-docker
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./data/sqlite3:/var/lib/sqlite3/data
    env_file:
      - .env
