apiVersion: v1
kind: Service
metadata:
  name: sqlite-service
spec:
  selector:
    app: sqlite
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31000
