name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sqlite-docker-image:$(date +%s)
    - name: Build and Push Image to Dockerhub
      uses: mr-smithers-excellent/docker-build-push@v4
      with: 
        image: azizurehmankhan/sqlite-test-app
        registry: docker.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        tag: ${{ steps.meta.outputs.tag }}

  
